image: ibmcom/swift-ubuntu:latest

stages:
  - test
  - build

review_service:
  stage: test
  script:
    - echo "Reviewing Naamio service" 
    - make build
    - make test
  only:
    - branches
  except: 
    - master

test_service:
  stage: test
  script:
    - echo "Testing Naamio service"
    - make test
  tags:
    - docker
  only:
    - master
  artifacts:
    paths:
    - .build/debug

build_release:
  stage: build
  script:
    - echo "Building release artifact for Naamio"
    - swift build -c release
  tags:
    - release
  when:
    - manual
  only:
    - release    